#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
# Repository path   : $HeadURL: $
# Last committed    : $Revision: $
# Last changed by   : $Author: $
# Last changed date : $Date: $
#

import tmEventSetup

from tmVhdlProducer.reporter import Reporter
from tmVhdlProducer import __version__

import argparse
import logging
import sys, os

EXIT_SUCCESS = 0
EXIT_FAILURE = 1

def parse():
    """Parse command line options."""
    parser = argparse.ArgumentParser(
        prog = 'tm-reporter',
        description = "Trigger Menu Reporter for uGT upgrade",
        epilog = "Report bugs to <bernhard.arnold@cern.ch>"
    )
    parser.add_argument('filename',
        type = os.path.abspath,
        help = "XML menu file to be loaded"
    )
    parser.add_argument('-o', '--outdir',
        default = os.getcwd(),
        type = os.path.abspath,
        help = "target directory to write output, default is current directory"
    )
    parser.add_argument('--version',
        action = 'version',
        version = "L1 Trigger Menu XML compiler version {0}".format(__version__),
    )
    return parser.parse_args()

def main():
    """Main routine."""
    args = parse()

    # Setup console logging
    logging.basicConfig(format = '%(levelname)s: %(message)s', level = logging.DEBUG)

    utm_root = os.environ.get("UTM_ROOT")
    logging.info("UTM_ROOT: %s", utm_root)
    if not utm_root:
        logging.error("no `UTM_ROOT' environment variable defined")
        return EXIT_FAILURE

    try:
        # Load XML menu and write report.
        logging.info("loading XML menu %s", args.filename)
        eventSetup = tmEventSetup.getTriggerMenu(args.filename)

        template_dir = os.path.join(utm_root, 'tmVhdlProducer', 'templates', 'doc')

        logging.info("generating menu documentation...")
        reporter = Reporter(template_dir, eventSetup)
        basename = eventSetup.getName()

        # Generate HTML output
        filename = os.path.join(args.outdir, '{basename}.html'.format(**locals()))
        logging.info("writing HTML documentation %s", filename)
        reporter.write_html(filename)

        # Generate TWIKI output
        filename = os.path.join(args.outdir, '{basename}.twiki'.format(**locals()))
        logging.info("writing TWIKI page template %s", filename)
        reporter.write_twiki(filename)

    except RuntimeError, message:
        logging.error(message)
        return EXIT_FAILURE

    return EXIT_SUCCESS

if __name__ == '__main__':
    sys.exit(main())
