#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
# Repository path   : $HeadURL: $
# Last committed    : $Revision: $
# Last changed by   : $Author: $
# Last changed date : $Date: $
#

import tmEventSetup

from tmVhdlProducer.reporter import Reporter
from tmVhdlProducer.vhdlproducer import VhdlProducer
from tmVhdlProducer.algodist import distribute, constraint_t
from tmVhdlProducer.algodist import MinModules, MaxModules
from tmVhdlProducer.algodist import kExternals
from tmVhdlProducer import __version__

import argparse
import subprocess
import logging
import sys, os
import re

EXIT_SUCCESS = 0
EXIT_FAILURE = 1
LOGFILE = 'tm-vhdlproducer.log'

SortingAsc = 'asc'
SortingDesc = 'desc'

DefaultRatio = 0.0
DefaultSorting = SortingAsc
DefaultOutputDir = os.getcwd()
from tmVhdlProducer.algodist import DefaultConfigFile

ConstraintTypes = {
    'ext': kExternals,
}
"""Mapping constraint types to esCondition types, provided for convenience."""

# -----------------------------------------------------------------------------
#  Helpers
# -----------------------------------------------------------------------------

def modules_t(value):
    """Validate number of modules input."""
    value = int(value)
    if 1 <= value <= MaxModules:
        return value
    raise ValueError(value)

def ratio_t(value):
    """Validates shadow ratio input."""
    value = float(value)
    if .0 <= value <= 1.:
        return value
    raise ValueError(value)

def getSvnRevision():
    """Returns local SVN revision number of set UTM_ROOT path."""
    rootdir = os.environ.get("UTM_ROOT")
    if not rootdir:
        raise RuntimeError("UTM_ROOT not set.")
    process = subprocess.Popen(['svnversion', rootdir], stdout=subprocess.PIPE)
    output = process.stdout.readlines()[0].strip()
    # match on 12345:12444MS -> ('12444', 'MS')
    result = re.match('(?:\w+\:)?(\d+)([A-Z]+)?', output)
    if not result:
        raise RuntimeError("utm directory is not an SVN directory")
    revision, modified = result.groups()
    return int(revision)

# -----------------------------------------------------------------------------
#  Command line parser
# -----------------------------------------------------------------------------

def parse():
    """Parse command line options."""
    parser = argparse.ArgumentParser(
        prog='tm-vhdlproducer',
        description="Trigger Menu VHDL Producer for uGT upgrade",
        epilog="Report bugs to <bernhard.arnold@cern.ch>"
    )
    parser.add_argument('menu',
        type=os.path.abspath,
        help="XML menu file to be loaded"
    )
    parser.add_argument('--modules',
        metavar='<n>',
        required=True,
        type=modules_t,
        help="number of modules ({0}-{1})".format(MinModules, MaxModules),
    )
    parser.add_argument('--ratio',
        metavar='<f>',
        default=DefaultRatio,
        type=ratio_t,
        help="algorithm shadow ratio (0.0 < ratio <= 1.0, default is {0})".format(DefaultRatio),
    )
    parser.add_argument('--sorting',
        metavar='asc|desc',
        default=DefaultSorting,
        choices=(SortingAsc, SortingDesc),
        help="sort order for condition weights ({0} or {1}, default is {2})".format(SortingAsc, SortingDesc, DefaultSorting),
    )
    parser.add_argument('--config',
        metavar='<file>',
        default=DefaultConfigFile,
        type=os.path.abspath,
        help="JSON resource configuration file (default is {0})".format(DefaultConfigFile),
    )
    parser.add_argument('--constraint',
        metavar='<condition:modules>',
        action='append',
        type=constraint_t,
        help="limit condition type to a specific module, valid types are: {0}".format(", ".join(ConstraintTypes.keys())),
    )
    parser.add_argument('--output',
        metavar='<dir>',
        default=DefaultOutputDir,
        type=os.path.abspath,
        help="directory to write VHDL producer output (default is {0})".format(DefaultOutputDir),
    )
    parser.add_argument('--dryrun',
        action='store_true',
        help="do not write any output to the file system"
    )
    parser.add_argument("--verbose",
        dest="verbose",
        action="store_true",
    )
    parser.add_argument('--version',
        action='version',
        version="L1 Trigger Menu VHDL producer version {0}".format(__version__),
    )
    return parser.parse_args()

# -----------------------------------------------------------------------------
#  Main routine
# -----------------------------------------------------------------------------

def main():
    """Main routine."""
    args = parse()

    # Setup console logging
    level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(format='%(levelname)s: %(message)s', level=level)

    logging.info("running VHDL producer...")

    utm_root = os.environ.get("UTM_ROOT")
    logging.info("UTM_ROOT: %s", utm_root)
    if not utm_root:
        logging.error("no `UTM_ROOT' environment variable defined")
        return EXIT_FAILURE

    logging.info("loading XML menu: %s", args.menu)
    eventSetup = tmEventSetup.getTriggerMenu(args.menu)
    output_dir = os.path.join(args.output, "{name}_m{modules}".format(name=eventSetup.getName(), modules=args.modules))

    # Prevent overwirting source menu
    dest = os.path.realpath(os.path.join(output_dir, 'xml'))
    orig = os.path.dirname(os.path.realpath(args.menu))
    if dest == orig:
        logging.error("%s is in %s directory which will be overwritten during the process", args.menu, dest)
        logging.error("     specified menu not in %s directory", dest)
        return EXIT_FAILURE

    if not args.dryrun:
        if os.path.isdir(output_dir):
            logging.error("directory `%s' already exists", output_dir)
            return EXIT_FAILURE
        else:
            os.makedirs(output_dir)

    if not args.dryrun:
        # Forward logs to file
        handler = logging.FileHandler(os.path.join(output_dir, LOGFILE), mode='a')
        handler.setFormatter(logging.Formatter(fmt='%(asctime)s %(levelname)s : %(message)s', datefmt='%Y-%m-%d %H:%M:%S'))
        handler.setLevel(level)
        logging.getLogger().addHandler(handler)

    # Fetch SVN revision
    revision = getSvnRevision()
    eventSetup.svnRevision = revision # HACK
    logging.info("svn revison r%s", revision)

    # Distribute algorithms, set sort order (asc or desc)
    reverse_sorting = (args.sorting == 'desc')
    # Collect condition constraints
    constraints = {}
    if args.constraint:
        for k, v in args.constraint:
            constraints[ConstraintTypes[k]] = v
    # Run distibution
    collection = distribute(
        eventSetup=eventSetup,
        modules=args.modules,
        config=args.config,
        ratio=args.ratio,
        reverse_sorting=reverse_sorting,
        constraints=constraints
    )

    if args.dryrun:
        logging.info("skipped writing output (dryrun mode)")
    else:
        logging.info("writing VHDL modules...")
        template_dir = os.path.join(utm_root, 'tmVhdlProducer', 'templates', 'vhdl')
        producer = VhdlProducer(template_dir)
        producer.write(collection, output_dir)
        logging.info("writing updated XML file %s", args.menu)
        filename = producer.writeXmlMenu(args.menu, os.path.join(output_dir, 'xml')) # TODO

        # Load output XML
        eventSetup = tmEventSetup.getTriggerMenu(filename)

        # Write menu documentation.
        logging.info("generating menu documentation...")
        template_dir = os.path.join(utm_root, 'tmVhdlProducer', 'templates', 'doc')
        reporter = Reporter(template_dir, eventSetup)
        basename = eventSetup.getName()

        # Generate HTML output
        filename = os.path.join(output_dir, 'doc', '{basename}.html'.format(**locals()))
        logging.info("writing HTML documentation %s", filename)
        reporter.write_html(filename)

        # Generate TWIKI output
        filename = os.path.join(output_dir, 'doc', '{basename}.twiki'.format(**locals()))
        logging.info("writing TWIKI page template %s", filename)
        reporter.write_twiki(filename)

    logging.info("done.")

    return EXIT_SUCCESS

if __name__ == '__main__':
    sys.exit(main())
